using Market.Domain.Entity.HR;
using Market.Infrastucture.Persistence;

namespace Market.Infrastucture.Seeders;
/// <summary>
/// Seeds the database with country key data if no data exists.
/// </summary>
/// <remarks>This class checks if the database is accessible and whether the <c>CountryKeys</c> table is empty. 
/// If the table is empty, it populates it with a predefined list of country keys and saves the changes.</remarks>
/// <param name="dbContext">The System DbContext</param>
internal class CountryKeySeeder(AppDbContext dbContext) : ICountryKeySeeder
{
    public async Task SeedAsync()
    {
        if (await dbContext.Database.CanConnectAsync())
        {
            if (!dbContext.CountryKeys.Any())
            {
                var countryKeys = GetCountryKeys();
                await dbContext.CountryKeys.AddRangeAsync(countryKeys);
                await dbContext.SaveChangesAsync();
            }
        }

    }
    // This method returns a list of predefined country keys.
    private IEnumerable<CountryKey> GetCountryKeys()
    {
        return new List<CountryKey>
        {
            #region List of Country Keys
            new CountryKey { CountryName = "Albania", Key = "+355" },
            new CountryKey { CountryName = "Afghanistan", Key = "+93" },
            new CountryKey { CountryName = "Algeria", Key = "+213" },
            new CountryKey { CountryName = "Andorra", Key = "+376" },
            new CountryKey { CountryName = "Angola", Key = "+244" },
            new CountryKey { CountryName = "Argentina", Key = "+54" },
            new CountryKey { CountryName = "Armenia", Key = "+374" },
            new CountryKey { CountryName = "Australia", Key = "+61" },
            new CountryKey { CountryName = "Austria", Key = "+43" },
            new CountryKey { CountryName = "Azerbaijan", Key = "+994" },
            new CountryKey { CountryName = "Bahamas", Key = "+1-242" },
            new CountryKey { CountryName = "Bahrain", Key = "+973" },
            new CountryKey { CountryName = "Bangladesh", Key = "+880" },
            new CountryKey { CountryName = "Barbados", Key = "+1-246" },
            new CountryKey { CountryName = "Belarus", Key = "+375" },
            new CountryKey { CountryName = "Belgium", Key = "+32" },
            new CountryKey { CountryName = "Belize", Key = "+501" },
            new CountryKey { CountryName = "Benin", Key = "+229" },
            new CountryKey { CountryName = "Bhutan", Key = "+975" },
            new CountryKey { CountryName = "Bolivia", Key = "+591" },
            new CountryKey { CountryName = "Bosnia and Herzegovina", Key = "+387" },
            new CountryKey { CountryName = "Botswana", Key = "+267" },
            new CountryKey { CountryName = "Brazil", Key = "+55" },
            new CountryKey { CountryName = "Brunei", Key = "+673" },
            new CountryKey { CountryName = "Bulgaria", Key = "+359" },
            new CountryKey { CountryName = "Burkina Faso", Key = "+226" },
            new CountryKey { CountryName = "Burundi", Key = "+257" },
            new CountryKey { CountryName = "Cambodia", Key = "+855" },
            new CountryKey { CountryName = "Cameroon", Key = "+237" },
            new CountryKey { CountryName = "Canada", Key = "+1" },
            new CountryKey { CountryName = "Cape Verde", Key = "+238" },
            new CountryKey { CountryName = "Central African Republic", Key = "+236" },
            new CountryKey { CountryName = "Chad", Key = "+235" },
            new CountryKey { CountryName = "Chile", Key = "+56" },
            new CountryKey { CountryName = "China", Key = "+86" },
            new CountryKey { CountryName = "Colombia", Key = "+57" },
            new CountryKey { CountryName = "Comoros", Key = "+269" },
            new CountryKey { CountryName = "Congo (Brazzaville)", Key = "+242" },
            new CountryKey { CountryName = "Congo (Kinshasa)", Key = "+243" },
            new CountryKey { CountryName = "Costa Rica", Key = "+506" },
            new CountryKey { CountryName = "Croatia", Key = "+385" },
            new CountryKey { CountryName = "Cuba", Key = "+53" },
            new CountryKey { CountryName = "Cyprus", Key = "+357" },
            new CountryKey { CountryName = "Czech Republic", Key = "+420" },
            new CountryKey { CountryName = "Denmark", Key = "+45" },
            new CountryKey { CountryName = "Djibouti", Key = "+253" },
            new CountryKey { CountryName = "Dominica", Key = "+1-767" },
            new CountryKey { CountryName = "Dominican Republic", Key = "+1-809" },
            new CountryKey { CountryName = "Ecuador", Key = "+593" },
            new CountryKey { CountryName = "Egypt", Key = "+20" },
            new CountryKey { CountryName = "El Salvador", Key = "+503" },
            new CountryKey { CountryName = "Equatorial Guinea", Key = "+240" },
            new CountryKey { CountryName = "Eritrea", Key = "+291" },
            new CountryKey { CountryName = "Estonia", Key = "+372" },
            new CountryKey { CountryName = "Eswatini", Key = "+268" },
            new CountryKey { CountryName = "Ethiopia", Key = "+251" },
            new CountryKey { CountryName = "Fiji", Key = "+679" },
            new CountryKey { CountryName = "Finland", Key = "+358" },
            new CountryKey { CountryName = "France", Key = "+33" },
            new CountryKey { CountryName = "Gabon", Key = "+241" },
            new CountryKey { CountryName = "Gambia", Key = "+220" },
            new CountryKey { CountryName = "Georgia", Key = "+995" },
            new CountryKey { CountryName = "Germany", Key = "+49" },
            new CountryKey { CountryName = "Ghana", Key = "+233" },
            new CountryKey { CountryName = "Greece", Key = "+30" },
            new CountryKey { CountryName = "Grenada", Key = "+1-473" },
            new CountryKey { CountryName = "Guatemala", Key = "+502" },
            new CountryKey { CountryName = "Guinea", Key = "+224" },
            new CountryKey { CountryName = "Guinea-Bissau", Key = "+245" },
            new CountryKey { CountryName = "Guyana", Key = "+592" },
            new CountryKey { CountryName = "Haiti", Key = "+509" },
            new CountryKey { CountryName = "Honduras", Key = "+504" },
            new CountryKey { CountryName = "Hungary", Key = "+36" },
            new CountryKey { CountryName = "Iceland", Key = "+354" },
            new CountryKey { CountryName = "India", Key = "+91" },
            new CountryKey { CountryName = "Indonesia", Key = "+62" },
            new CountryKey { CountryName = "Iran", Key = "+98" },
            new CountryKey { CountryName = "Iraq", Key = "+964" },
            new CountryKey { CountryName = "Ireland", Key = "+353" },
            new CountryKey { CountryName = "Israel", Key = "+972" },
            new CountryKey { CountryName = "Italy", Key = "+39" },
            new CountryKey { CountryName = "Ivory Coast", Key = "+225" },
            new CountryKey { CountryName = "Jamaica", Key = "+1-876" },
            new CountryKey { CountryName = "Japan", Key = "+81" },
            new CountryKey { CountryName = "Jordan", Key = "+962" },
            new CountryKey { CountryName = "Kazakhstan", Key = "+7" },
            new CountryKey { CountryName = "Kenya", Key = "+254" },
            new CountryKey { CountryName = "Kiribati", Key = "+686" },
            new CountryKey { CountryName = "Kuwait", Key = "+965" },
            new CountryKey { CountryName = "Kyrgyzstan", Key = "+996" },
            new CountryKey { CountryName = "Laos", Key = "+856" },
            new CountryKey { CountryName = "Latvia", Key = "+371" },
            new CountryKey { CountryName = "Lebanon", Key = "+961" },
            new CountryKey { CountryName = "Lesotho", Key = "+266" },
            new CountryKey { CountryName = "Liberia", Key = "+231" },
            new CountryKey { CountryName = "Libya", Key = "+218" },
            new CountryKey { CountryName = "Liechtenstein", Key = "+423" },
            new CountryKey { CountryName = "Lithuania", Key = "+370" },
            new CountryKey { CountryName = "Luxembourg", Key = "+352" },
            new CountryKey { CountryName = "Madagascar", Key = "+261" },
            new CountryKey { CountryName = "Malawi", Key = "+265" },
            new CountryKey { CountryName = "Malaysia", Key = "+60" },
            new CountryKey { CountryName = "Maldives", Key = "+960" },
            new CountryKey { CountryName = "Mali", Key = "+223" },
            new CountryKey { CountryName = "Malta", Key = "+356" },
            new CountryKey { CountryName = "Marshall Islands", Key = "+692" },
            new CountryKey { CountryName = "Mauritania", Key = "+222" },
            new CountryKey { CountryName = "Mauritius", Key = "+230" },
            new CountryKey { CountryName = "Mexico", Key = "+52" },
            new CountryKey { CountryName = "Micronesia", Key = "+691" },
            new CountryKey { CountryName = "Moldova", Key = "+373" },
            new CountryKey { CountryName = "Monaco", Key = "+377" },
            new CountryKey { CountryName = "Mongolia", Key = "+976" },
            new CountryKey { CountryName = "Montenegro", Key = "+382" },
            new CountryKey { CountryName = "Morocco", Key = "+212" },
            new CountryKey { CountryName = "Mozambique", Key = "+258" },
            new CountryKey { CountryName = "Myanmar", Key = "+95" },
            new CountryKey { CountryName = "Namibia", Key = "+264" },
            new CountryKey { CountryName = "Nauru", Key = "+674" },
            new CountryKey { CountryName = "Nepal", Key = "+977" },
            new CountryKey { CountryName = "Netherlands", Key = "+31" },
            new CountryKey { CountryName = "New Zealand", Key = "+64" },
            new CountryKey { CountryName = "Nicaragua", Key = "+505" },
            new CountryKey { CountryName = "Niger", Key = "+227" },
            new CountryKey { CountryName = "Nigeria", Key = "+234" },
            new CountryKey { CountryName = "North Korea", Key = "+850" },
            new CountryKey { CountryName = "North Macedonia", Key = "+389" },
            new CountryKey { CountryName = "Norway", Key = "+47" },
            new CountryKey { CountryName = "Oman", Key = "+968" },
            new CountryKey { CountryName = "Pakistan", Key = "+92" },
            new CountryKey { CountryName = "Palau", Key = "+680" },
            new CountryKey { CountryName = "Palestine", Key = "+970" },
            new CountryKey { CountryName = "Panama", Key = "+507" },
            new CountryKey { CountryName = "Papua New Guinea", Key = "+675" },
            new CountryKey { CountryName = "Paraguay", Key = "+595" },
            new CountryKey { CountryName = "Peru", Key = "+51" },
            new CountryKey { CountryName = "Philippines", Key = "+63" },
            new CountryKey { CountryName = "Poland", Key = "+48" },
            new CountryKey { CountryName = "Portugal", Key = "+351" },
            new CountryKey { CountryName = "Qatar", Key = "+974" },
            new CountryKey { CountryName = "Romania", Key = "+40" },
            new CountryKey { CountryName = "Russia", Key = "+7" },
            new CountryKey { CountryName = "Rwanda", Key = "+250" },
            new CountryKey { CountryName = "Saint Kitts and Nevis", Key = "+1-869" },
            new CountryKey { CountryName = "Saint Lucia", Key = "+1-758" },
            new CountryKey { CountryName = "Saint Vincent", Key = "+1-784" },
            new CountryKey { CountryName = "Samoa", Key = "+685" },
            new CountryKey { CountryName = "San Marino", Key = "+378" },
            new CountryKey { CountryName = "Saudi Arabia", Key = "+966" },
            new CountryKey { CountryName = "Senegal", Key = "+221" },
            new CountryKey { CountryName = "Serbia", Key = "+381" },
            new CountryKey { CountryName = "Seychelles", Key = "+248" },
            new CountryKey { CountryName = "Sierra Leone", Key = "+232" },
            new CountryKey { CountryName = "Singapore", Key = "+65" },
            new CountryKey { CountryName = "Slovakia", Key = "+421" },
            new CountryKey { CountryName = "Slovenia", Key = "+386" },
            new CountryKey { CountryName = "Solomon Islands", Key = "+677" },
            new CountryKey { CountryName = "Somalia", Key = "+252" },
            new CountryKey { CountryName = "South Africa", Key = "+27" },
            new CountryKey { CountryName = "South Korea", Key = "+82" },
            new CountryKey { CountryName = "South Sudan", Key = "+211" },
            new CountryKey { CountryName = "Spain", Key = "+34" },
            new CountryKey { CountryName = "Sri Lanka", Key = "+94" },
            new CountryKey { CountryName = "Sudan", Key = "+249" },
            new CountryKey { CountryName = "Suriname", Key = "+597" },
            new CountryKey { CountryName = "Sweden", Key = "+46" },
            new CountryKey { CountryName = "Switzerland", Key = "+41" },
            new CountryKey { CountryName = "Syria", Key = "+963" },
            new CountryKey { CountryName = "Taiwan", Key = "+886" },
            new CountryKey { CountryName = "Tajikistan", Key = "+992" },
            new CountryKey { CountryName = "Tanzania", Key = "+255" },
            new CountryKey { CountryName = "Thailand", Key = "+66" },
            new CountryKey { CountryName = "Togo", Key = "+228" },
            new CountryKey { CountryName = "Tonga", Key = "+676" },
            new CountryKey { CountryName = "Trinidad and Tobago", Key = "+1-868" },
            new CountryKey { CountryName = "Tunisia", Key = "+216" },
            new CountryKey { CountryName = "Turkey", Key = "+90" },
            new CountryKey { CountryName = "Turkmenistan", Key = "+993" },
            new CountryKey { CountryName = "Tuvalu", Key = "+688" },
            new CountryKey { CountryName = "Uganda", Key = "+256" },
            new CountryKey { CountryName = "Ukraine", Key = "+380" },
            new CountryKey { CountryName = "United Arab Emirates", Key = "+971" },
            new CountryKey { CountryName = "United Kingdom", Key = "+44" },
            new CountryKey { CountryName = "United States", Key = "+1" },
            new CountryKey { CountryName = "Uruguay", Key = "+598" },
            new CountryKey { CountryName = "Uzbekistan", Key = "+998" },
            new CountryKey { CountryName = "Vanuatu", Key = "+678" },
            new CountryKey { CountryName = "Vatican City", Key = "+379" },
            new CountryKey { CountryName = "Venezuela", Key = "+58" },
            new CountryKey { CountryName = "Vietnam", Key = "+84" },
            new CountryKey { CountryName = "Yemen", Key = "+967" },
            new CountryKey { CountryName = "Zambia", Key = "+260" },
            new CountryKey { CountryName = "Zimbabwe", Key = "+263" }

            #endregion
        };
    }
}
